name: CI

on: push

jobs:
  check:
    uses: jill64/workflows/.github/workflows/check.yml@main
  publish-pages:
    permissions:
      pages: write
      id-token: write
    uses: jill64/workflows/.github/workflows/publish-pages.yml@main
